"""Regenerate src/app/design.css from the artboard stylesheets.

    python tools/port/build-css.py

THREE THINGS TO KNOW BEFORE RUNNING THIS.

1. Do not run it. It DOES run - this docstring said for a long time that it
   could not, because design-src/artboards/ was not checked in and the first
   open() would fail; measured 22 Sep 2026, the directory is present and
   git-tracked with all nine boards and canvas.json, i.e. every input sheet()
   opens. So design.css is maintained in place by choice, and the "regenerate
   rather than hand-tuning" header this script writes into it is a hazard
   rather than an instruction. Points 2 and 3 are what it would cost.

2. It emits the canvas stylesheet verbatim - which means physical left/right
   properties, undoing the RTL conversion (BUILD-SPEC 12, section 7). Follow it
   immediately with:

       python tools/port/logical-css.py --write

   check:logical fails the build if that is forgotten, so this is a reminder
   rather than the safeguard.

3. It would also undo the .inp contrast fix, and NOTHING would catch that.
   All nine boards carry `color: #7D796F` on .inp; that measures 3.95:1 on
   --paper where AA requires 4.5:1, and design.css now uses var(--muted)
   (4.83:1) at both breakpoints instead. No gate reads the stylesheets for
   colour - check:contrast walks the token table, so a non-token colour is out
   of its scope by construction - so this one comes back silently. Fix the
   boards first if they are ever the source again.

   It would NOT undo the --faint collapse, and that is deliberate. TASKS.md
   Part 2a deleted the third text tier on 22 Sep 2026 (2.43:1 on --paper,
   2.67:1 on --white, against 4.5:1 for body text and 3:1 for large text - it
   missed both, so no type size could have rescued it; the lightest passing
   colour on that hue is 1.06:1 from --muted, i.e. indistinguishable). The
   same substitution was applied to all nine boards - the declaration removed,
   every var(--faint) and every inline #A29E94 now var(--muted) - precisely
   because point 3 above proves a fix that lives only in the output is one
   regeneration away from being lost, and no gate would report it.

The desktop (Main/Desktop2-4) and mobile (Mobile1-5) boards each carry one
complete stylesheet. Both are copied verbatim except for the edits listed in
PATCHES, which are what turn two fixed-width canvases into one fluid page.
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ART = os.path.join(HERE, '..', '..', 'design-src', 'artboards')
OUT = os.path.join(HERE, '..', '..', 'src', 'app', 'design.css')

# The canvas hardcodes the webfont stacks; the app loads them through next/font.
FONTS = [
    ('"Newsreader", "Times New Roman", Georgia, serif',
     'var(--font-newsreader), "Times New Roman", Georgia, serif'),
    ('"Instrument Sans", "Helvetica Neue", Helvetica, Arial, sans-serif',
     'var(--font-instrument), "Helvetica Neue", Helvetica, Arial, sans-serif'),
    ('"Geist Mono", "SF Mono", Menlo, Consolas, monospace',
     'var(--font-geist-mono), "SF Mono", Menlo, Consolas, monospace'),
]

# Fixed artboard geometry -> fluid page. Everything else is untouched.
PATCHES = {
    'desktop': [
        ('.page { width: 1440px; min-height: 100%; background: var(--paper); overflow: hidden; }',
         '.page { width: 100%; max-width: 1440px; margin: 0 auto; min-height: 100%; background: var(--paper); overflow: hidden; }'),
        ('.wrap { padding-left: 120px; padding-right: 120px; }',
         '.wrap { padding-left: clamp(24px, 8.334vw, 120px); padding-right: clamp(24px, 8.334vw, 120px); }'),
    ],
    'mobile': [
        ('.page { width: 390px; min-height: 100%; background: var(--paper); overflow: hidden; }',
         '.page { width: 100%; margin: 0 auto; min-height: 100%; background: var(--paper); overflow: hidden; }'),
    ],
}

def sheet(board, which):
    s = open(os.path.join(ART, board + '.dc.html'), encoding='utf-8').read()
    css = re.search(r'<style>(.*?)</style>', s, re.S).group(1).strip()
    for a, b in FONTS + PATCHES[which]:
        assert a in css, 'stale patch, not found in %s: %s' % (board, a[:60])
        css = css.replace(a, b)
    return css

indent = lambda t: '\n'.join(('  ' + l if l.strip() else l) for l in t.splitlines())

open(OUT, 'w', encoding='utf-8').write("""/* HelloVerify - design system, ported verbatim from the Claude Design canvas.
   Generated by tools/port/build-css.py. Regenerate rather than hand-tuning.

   The two artboard stylesheets are kept in DISJOINT media queries on purpose.
   The mobile board is a complete stylesheet, not an override layer: where its
   rules omit a property the desktop rule declares (say .role's letter-spacing),
   letting desktop cascade underneath would apply a value that board never had. */

/* ============ DESKTOP - artboards Main / Desktop2-4 ============ */
@media (min-width: 1081px) {
%s
}

/* ============ MOBILE - artboards Mobile1-5 ============ */
@media (max-width: 1080px) {
%s
}

/* ============ RESPONSIVE SWITCH ============
   Desktop and mobile artboards have different element trees, not just different
   sizes. Both are rendered and one is swapped out here. */
.dsk { display: block; }
.mob { display: none; }
@media (max-width: 1080px) {
  .dsk { display: none; }
  .mob { display: block; }
  /* No tablet artboard exists. Below the desktop gutters the mobile board is the
     honest layout, so it is held to a phone-ish column and centred. */
  .page { max-width: 720px; }
}

/* ============ FIXES ON TOP OF THE CANVAS ============
   Deliberate deviations, each traceable to a review note. */

/* The numbers reveal clips its own digits: at 176px/0.9 line-height the glyph
   em box is ~9px taller than the line box, and .big's overflow:hidden (needed
   for the rise animation) shaves the tops of 20M+/2,000+/120+/33+. Give the
   clip box headroom the same way the canvas already does at the bottom
   (padding offset by an equal negative margin), so layout does not move. */
.big { padding-top: 0.1em; margin-top: -0.1em; }
""" % (indent(sheet('Main', 'desktop')), indent(sheet('Mobile', 'mobile'))))
print('wrote', os.path.relpath(OUT, os.path.join(HERE, '..', '..')))
