"""Physical -> logical CSS properties, for RTL (BUILD-SPEC §12, §7).

    python tools/port/logical-css.py            # report only
    python tools/port/logical-css.py --write    # rewrite in place

§12 requires "CSS logical properties only, lint-enforced", because §7 ships an
Arabic locale and a stylesheet written in left/right cannot be mirrored: every
`margin-left` stays on the left when the document direction flips, so the
layout comes apart rather than reflecting.

WHY THIS IS A SEPARATE SCRIPT AND NOT A PATCH IN build-css.py.

`design.css` says "Generated by tools/port/build-css.py. Regenerate rather than
hand-tuning." That instruction cannot be followed here: the generator reads
`design-src/artboards/*.dc.html`, and **that directory is not in this tree**.
Re-running it fails at the first `open()`. So the canvas output can only be
transformed in place.

`pages.css` is the opposite case - it was never generated, it is hand-written
for everything built after the port. Same transform, different provenance.

So this is written to be idempotent and to run over both, and `build-css.py`
imports it so that a future regeneration (if the artboards ever return) emits
logical properties too rather than silently undoing this.

ONLY THE INLINE AXIS IS CONVERTED, and that is the point rather than laziness.
In a horizontal writing mode RTL flips the INLINE axis only; `margin-top` means
the same thing in Arabic as in English. Converting the 156 block-axis
properties would be churn across a design-complete stylesheet with no
behavioural effect and a real chance of a typo. Measured in this repo:

    inline axis (must convert):  left/right insets 132, margin 25,
                                 border 18, padding 9, text-align 13
    block axis (left alone):     margin-top/bottom 113, padding-top/bottom 43

VALUES ARE NOT TOUCHED except for `text-align` and `float`, whose `left`/`right`
keywords are themselves directional. `background-position: left top` and
`transform-origin: right` are deliberately left alone: they position painted
artwork, not layout, and flipping a photograph's focal point is usually wrong.
Those are listed by the report so the decision is visible rather than implied.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TARGETS = [
    os.path.join(HERE, '..', '..', 'src', 'app', 'design.css'),
    os.path.join(HERE, '..', '..', 'src', 'app', 'pages.css'),
]

# Property renames. Longest first so `border-left-width` is not half-matched by
# `border-left`.
PROPERTY_MAP = [
    ('margin-left', 'margin-inline-start'),
    ('margin-right', 'margin-inline-end'),
    ('padding-left', 'padding-inline-start'),
    ('padding-right', 'padding-inline-end'),
    ('border-left-width', 'border-inline-start-width'),
    ('border-right-width', 'border-inline-end-width'),
    ('border-left-color', 'border-inline-start-color'),
    ('border-right-color', 'border-inline-end-color'),
    ('border-left-style', 'border-inline-start-style'),
    ('border-right-style', 'border-inline-end-style'),
    ('border-left', 'border-inline-start'),
    ('border-right', 'border-inline-end'),
    ('scroll-margin-left', 'scroll-margin-inline-start'),
    ('scroll-padding-left', 'scroll-padding-inline-start'),
]

# Bare `left:` / `right:` are the inset properties. Matched only at property
# position - after `{`, `;`, or line start - so `border-left:` (preceded by a
# hyphen) and any value containing the word are untouched.
INSET = re.compile(r'(^|[;{]|\n)(\s*)(left|right)(\s*:)', re.M)
INSET_MAP = {'left': 'inset-inline-start', 'right': 'inset-inline-end'}

# Directional KEYWORDS, where the value is the thing that flips.
VALUE_RULES = [
    (re.compile(r'(text-align\s*:\s*)left\b'), r'\1start'),
    (re.compile(r'(text-align\s*:\s*)right\b'), r'\1end'),
    (re.compile(r'(float\s*:\s*)left\b'), r'\1inline-start'),
    (re.compile(r'(float\s*:\s*)right\b'), r'\1inline-end'),
    (re.compile(r'(clear\s*:\s*)left\b'), r'\1inline-start'),
    (re.compile(r'(clear\s*:\s*)right\b'), r'\1inline-end'),
]

# Reported, never rewritten - see the module docstring.
PAINT = re.compile(r'(background-position|transform-origin|object-position)\s*:[^;}]*\b(left|right)\b')


def convert(css):
    """Returns (converted, counts). Idempotent: logical input is unchanged."""
    counts = {}

    for physical, logical in PROPERTY_MAP:
        pattern = re.compile(r'(^|[;{\s])' + re.escape(physical) + r'(\s*:)', re.M)
        css, n = pattern.subn(lambda m: m.group(1) + logical + m.group(2), css)
        if n:
            counts[physical] = n

    def inset(m):
        return m.group(1) + m.group(2) + INSET_MAP[m.group(3)] + m.group(4)

    css, n = INSET.subn(inset, css)
    if n:
        counts['left/right insets'] = n

    for pattern, repl in VALUE_RULES:
        css, n = pattern.subn(repl, css)
        if n:
            counts[pattern.pattern.split('\\')[0].strip('(')] = counts.get('keywords', 0) + n

    return css, counts


def main():
    write = '--write' in sys.argv
    total = 0
    for path in TARGETS:
        with open(path, encoding='utf-8') as f:
            before = f.read()
        after, counts = convert(before)
        name = os.path.basename(path)

        if counts:
            print('%s:' % name)
            for k, v in sorted(counts.items(), key=lambda x: -x[1]):
                print('    %4d  %s' % (v, k))
            total += sum(counts.values())
        else:
            print('%s: already logical' % name)

        painted = PAINT.findall(before)
        if painted:
            print('    (%d paint-positioning value(s) left alone by design)' % len(painted))

        if write and after != before:
            with open(path, 'w', encoding='utf-8', newline='\n') as f:
                f.write(after)

    print('')
    if write:
        print('rewrote %d declaration(s)' % total)
    else:
        print('%d declaration(s) would change; pass --write to apply' % total)


if __name__ == '__main__':
    main()
