/** BUILD-SPEC §9.1's budgets, measured against the build output.
 *
 *  §9.1 says "enforced in CI, not aspirational" and specifies `lhci autorun` on
 *  every PR against the preview deployment. There is no CI in this repo and no
 *  preview deployment, and the budget file splits cleanly in two anyway:
 *
 *    - `resourceSizes` and `resourceCounts` are properties of the BUILD. They
 *      are deterministic, need no browser, and are what this measures.
 *    - `timings` (LCP, CLS, TBT) are properties of a DEPLOYMENT — they depend
 *      on the network, the CDN and the device. They belong with §14.3's
 *      post-deploy contract test, for the same reason §14.3 exists at all: a
 *      build being correct is not the deployment being correct.
 *
 *  Sizes are BROTLI, not gzip and not raw, because that is what Cloud Run
 *  behind Cloud CDN will actually put on the wire (§3.6) and what Lighthouse
 *  would count. Fonts are counted raw: WOFF2 is already brotli-compressed
 *  internally and re-compressing it measures nothing.
 *
 *  TWO TIERS, and the second one is the point.
 *
 *  `SPEC` is §9.1 verbatim. Two of its five numbers are not met today and the
 *  gate says so on every run rather than hiding it.
 *
 *  `CEILING` is what the build actually produces, plus a little headroom. It is
 *  what FAILS the build. A gate pinned to an unreachable target either gets
 *  switched off or gets its target quietly raised, and both are worse than an
 *  honest regression guard: this one cannot be passed by accident, it makes the
 *  remaining gap visible every time it runs, and it stops the gap growing.
 *
 *  THE FONT GAP, measured rather than asserted. §9.1 wants 60 KB; the build
 *  emits 242 KB. `npm run build:fonts` already took it from 324 KB by subsetting
 *  to the 133 characters the site renders. The rest is the type system itself —
 *  three families, and a serif carrying two variable axes in roman and italic:
 *
 *      Newsreader roman, glyph-subset, both axes ......... 82 KB
 *      ... with `opsz` pinned .............................. 35 KB
 *      ... with `opsz` pinned and `wght` 400-600 ........... 23 KB
 *      ... fully static (opsz 40, wght 400) ................ 13 KB
 *
 *  So closing it means pinning `opsz` — and the serif runs from 15px captions
 *  to a 176px display number, so `font-optical-sizing` is doing visible work
 *  across that range. Even pinning every axis on all four faces lands near
 *  90 KB with three families; §9.3's own "maximum two families" would have to
 *  go with it. That is a DESIGN.md decision, not a build step, which is why
 *  this file records the number instead of quietly changing the type.
 *
 *  IMAGES ARE NOT MEASURED HERE, deliberately. `next/image` emits
 *  `/_next/image?url=…&w=…&q=…`, and those variants are generated by the
 *  optimizer at request time — they are not in the build output, so there is
 *  nothing on disk to weigh. Measuring the source files in `public/img`
 *  instead would report a number no visitor ever downloads. The image budget
 *  belongs with the timings, against a running origin.
 *
 *  Reads the build output, so run it after `next build`:
 *      node tools/perf/check-budgets.mjs
 */
import { readdir, readFile } from "node:fs/promises";
import { brotliCompressSync, constants } from "node:zlib";

import { htmlPages } from "../seo/build-output.mjs";

const root = new URL("../../", import.meta.url);

/** §9.1, verbatim. KB, compressed. */
const SPEC = {
  script: 120,
  stylesheet: 40,
  font: 60,
  total: 500,
  thirdParty: 5,
};

/** What the build produces today, plus ~3% headroom so that an incidental
 *  re-chunking does not fail the build while a real regression does. Lower
 *  these as the gap closes; never raise one without saying why in the diff. */
const CEILING = {
  /** HOMEPAGE V2 (Sep 2026, TASKS.md Part 12) reset all four, measured on the
   *  final integrated build rather than guessed. The redesign added eighteen
   *  interactive sections; two optimisation passes then took `/en` from 566.8
   *  to 548.6 KB, and pinning Newsreader's weight axis
   *  (`tools/perf/pin-serif-weight.mjs`) to 430.0 KB — under §9.1's 500.
   *
   *  RAISED, with the reason:
   *  - script 163 -> 188: /en measures 182.3 KB. The v2 islands' canvas engines
   *    (globe, trust graph, sun map, enterprise rings) already load on approach
   *    via `lib/whenNear.ts`; what stays eager is the stage code each section
   *    needs to paint and respond. Moving static SVG from client stages to the
   *    server was measured and rejected: −2.3 KB script, +2.3 KB document, total
   *    unchanged (it travels twice, HTML and flight). Still over §9.1's 120, as
   *    it was before v2 (162).
   *  - stylesheet 17 -> 41: /en measures 39.6 KB, inside §9.1's 40. Eighteen v2
   *    section sheets, each imported only by its own section; inner-page rules
   *    already split into `app/inner.css` so /en does not pay for them.
   *  - stylesheet 41 -> 42 (24 Sep 2026): /en measures 41.2 KB, now OVER §9.1's
   *    40. What moved it since 39.6: the SMB conversion pass, the real
   *    closing-band form (`v2/contact.css`) and the Employees / Customers /
   *    Businesses panels. Paid down on the way by deleting 58 `design.css`
   *    rules whose classes nothing in `src/` references (6.2 KB raw) and by
   *    trimming two flourishes from the new panels; what is left is the new
   *    UI itself. The next CSS on /en should come with a matching removal.
   *
   *  LOWERED, so the saving cannot quietly erode:
   *  - font 245 -> 127: 123.3 KB after the wght pin (was 241.9).
   *  - total 468 -> 443: 430.0 KB.
   *
   *  Each is the measurement plus ~3%, the headroom rule stated above. */
  script: 188,
  stylesheet: 42,
  font: 127,
  total: 443,
  thirdParty: 5,
};

const brotli = (buf) =>
  brotliCompressSync(buf, { params: { [constants.BROTLI_PARAM_QUALITY]: 11 } }).length;

const KB = (n) => n / 1024;

const failures = [];
const pages = await htmlPages(root);

/** Static assets are shared across pages, so the same chunk is compressed once
 *  and reused. Without this the 56-page walk recompresses ~450 files at
 *  quality 11 and takes minutes instead of seconds. */
const sizeCache = new Map();
async function assetSize(ref) {
  if (sizeCache.has(ref)) return sizeCache.get(ref);
  const file = new URL(`.next${ref.replace("/_next", "")}`, root);
  let size = 0;
  try {
    const buf = await readFile(file);
    // WOFF2 is already brotli inside; re-compressing measures nothing.
    size = /\.(woff2?|otf|ttf)$/.test(ref) ? buf.length : brotli(buf);
  } catch {
    size = 0; // not in the build output — reported by the SEO gates, not here
  }
  sizeCache.set(ref, size);
  return size;
}

/** §9.2: "No raw <img> in components — lint rule." There is no linter wired
 *  up here, and the rule is one line of grep, so it lives with the budget it
 *  protects: a raw <img> skips the optimizer entirely, shipping the source file
 *  at full size to every visitor, and none of the size budgets above would
 *  notice — the image is not in the build output to be weighed.
 *
 *  Source check, not build output, deliberately. By the time it reaches the
 *  HTML a raw <img> and an optimized one look nearly identical; the place to
 *  catch it is where someone typed it. Currently zero across 24 files that use
 *  `next/image`.
 */
{
  const bad = [];
  const scan = async (dir) => {
    for (const item of await readdir(new URL(dir, root), { withFileTypes: true })) {
      if (item.isDirectory()) await scan(`${dir}${item.name}/`);
      else if (item.name.endsWith(".tsx")) {
        const src = await readFile(new URL(`${dir}${item.name}`, root), "utf8");
        for (const m of src.matchAll(/<img[\s>]/g)) {
          const line = src.slice(0, m.index).split("\n").length;
          bad.push(`${dir}${item.name}:${line}`);
        }
      }
    }
  };
  await scan("src/");
  if (bad.length) {
    failures.push(
      `${bad.length} raw <img> in components (§9.2 wants next/image everywhere): ` +
        bad.join(", "),
    );
  }
}

const rows = [];
for (const [path, file] of pages) {
  if (path.startsWith("/_")) continue; // /_not-found, /_global-error
  const html = await readFile(new URL(file, root), "utf8");

  const totals = { script: 0, stylesheet: 0, font: 0 };
  for (const m of html.matchAll(/(?:src|href)="(\/_next\/static\/[^"]+)"/g)) {
    const ref = m[1];
    const kind = ref.endsWith(".js")
      ? "script"
      : ref.endsWith(".css")
        ? "stylesheet"
        : /\.(woff2?|otf|ttf)$/.test(ref)
          ? "font"
          : null;
    if (kind) totals[kind] += await assetSize(ref);
  }

  /** The document itself counts toward `total` — it is the largest single
   *  transfer on several of these pages, because the RSC flight payload is
   *  inlined into it. Leaving it out would let the total budget pass while the
   *  page got heavier. */
  const document = brotli(Buffer.from(html));

  /** §9.4: "maximum 5 third-party requests on any page, none render-blocking."
   *  Counted as distinct external ORIGINS referenced by a src/href, which is
   *  the thing that costs a connection. */
  const origins = new Set(
    [
      // Anything the browser FETCHES: a src on any element, or an href on a
      // <link> (stylesheet, preload, preconnect). Deliberately NOT <a href> —
      // this site links out to app.helloverify.com from every pricing card, and
      // a link the user may click is not a request the page makes. Counting it
      // would report a third-party cost that does not exist.
      ...[...html.matchAll(/\bsrc="(https?:\/\/[^"]+)"/g)].map((m) => m[1]),
      ...[...html.matchAll(/<link\b[^>]*?\bhref="(https?:\/\/[^"]+)"/g)].map((m) => m[1]),
    ].map((u) => new URL(u).origin),
  );
  origins.delete("https://www.helloverify.com"); // our own canonical/OG URLs

  rows.push({
    path,
    script: KB(totals.script),
    stylesheet: KB(totals.stylesheet),
    font: KB(totals.font),
    total: KB(totals.script + totals.stylesheet + totals.font + document),
    thirdParty: origins.size,
  });
}

/** The worst page per metric — a per-page budget is only met if every page
 *  meets it, so the maximum is the number that matters. */
const worst = {};
for (const metric of ["script", "stylesheet", "font", "total", "thirdParty"]) {
  worst[metric] = rows.reduce((a, b) => (b[metric] > a[metric] ? b : a));
}

console.log(`pages measured: ${rows.length}   (brotli; fonts raw; images excluded — see header)\n`);
console.log("  metric        worst page                          value    §9.1   ceiling");
for (const metric of ["script", "stylesheet", "font", "total", "thirdParty"]) {
  const row = worst[metric];
  const value = row[metric];
  const unit = metric === "thirdParty" ? "" : " KB";
  const overSpec = value > SPEC[metric];
  const overCeiling = value > CEILING[metric];
  const mark = overCeiling ? "FAIL" : overSpec ? "over §9.1" : "ok";
  console.log(
    `  ${metric.padEnd(12)}  ${row.path.padEnd(34)} ` +
      `${value.toFixed(1).padStart(6)}${unit}  ${String(SPEC[metric]).padStart(5)}  ` +
      `${String(CEILING[metric]).padStart(6)}   ${mark}`,
  );
  if (overCeiling) {
    failures.push(
      `${metric} is ${value.toFixed(1)}${unit} on ${row.path}, over the ${CEILING[metric]}${unit} ceiling`,
    );
  }
}

const gaps = ["script", "stylesheet", "font", "total", "thirdParty"].filter(
  (m) => worst[m][m] > SPEC[m],
);

console.log("");
if (failures.length) {
  for (const f of failures) console.log(`  x ${f}`);
  console.log(
    `\nFAIL - ${failures.length} budget(s) regressed past the ceiling.\n` +
      "       Either undo the regression, or lower the code's cost. Raising a\n" +
      "       CEILING is a decision that belongs in the diff with a reason.",
  );
  process.exit(1);
}

if (gaps.length) {
  console.log(
    `PASS - no regression past the ceiling.\n` +
      `       ${gaps.length} metric(s) still short of §9.1: ${gaps.join(", ")}.\n` +
      "       See the header of this file for the measured font curve and why\n" +
      "       closing that one needs a DESIGN.md decision.",
  );
} else {
  console.log("PASS - every §9.1 budget met.");
}
process.exit(0);
