/** The reviewed facts about HelloVerify, stated once (BUILD-SPEC §11a.3, §11a.4).
 *
 *  §11a.4 requires `llms.txt` to carry "the hard numbers (20M+, 120+, 2000+,
 *  certifications)", and §11a.3 requires the `Organization` entity to match
 *  external profiles exactly. Both were about to restate figures that
 *  `app/[locale]/about/page.tsx` already carries — which is how "20M+" comes to
 *  be three strings in three files and two of them go stale.
 *
 *  SOURCES, and how conflicts between them were settled. The old site is at
 *  `D:\Projects\Application Frontend HV`; §8.2 and §8.3 both say "port" from it.
 *  It disagrees with this repo in several places, and where it does the newer
 *  reviewed copy wins and the conflict is recorded rather than quietly dropped:
 *
 *  - **Head office: Noida.** The old live schema
 *    (`src/components/StructuredData.tsx:45`) says Mumbai, its `seo.ts:50` says
 *    "Founded in Noida", and its contact page says "India, New Delhi" — four
 *    answers across two repos. Confirmed as Noida, which is what `/about`
 *    already said, so the schema running in production today is wrong.
 *  - **Six offices.** The old contact page lists four (New Delhi, Cairo, Dubai,
 *    Singapore); `/about` lists six. Confirmed as six — Manila and New York
 *    are real.
 *  - **LinkedIn.** The old repo carries two URLs: `/company/helloverify` in the
 *    schema and `/in/hello-verify-trust-line-06b895148/` in the footer, which
 *    is a personal-profile URL. Confirmed as the `/company/` one.
 *  - **NOW PORTED: ISO/IEC 27701, SOC 2 and ISO 9001.** Held back until 22 Sep
 *    2026 as unevidenced; confirmed real by the owner on that date and
 *    published here "according to the old site", so the old site's own spelling
 *    governs. They are published at `public/llms.txt:67` as "ISO/IEC 27001 and
 *    ISO/IEC 27701 certified" (generated by
 *    `scripts/generate-seo-files.mjs:180`), at `src/config/seo.ts:50` as
 *    "ISO 27001 & SOC 2 compliance", and at
 *    `public/cms/en/educationAuthorities.base.json:126` as "HelloVerify is ISO
 *    9001 and 27701 certified and GDPR compliant" — hence "ISO/IEC 27701"
 *    rather than "ISO 27701", "SOC 2 compliant" rather than "SOC 2 certified",
 *    and "ISO 9001 certified" with no `/IEC`, which is also the correct
 *    designation since ISO 9001 is an ISO standard and not a joint ISO/IEC one.
 *    The strength of that evidence is stated on the entries themselves in
 *    `CREDENTIALS` below, because it is weaker than the evidence behind every
 *    other line there.
 *
 *  THE SOURCE OF TRUTH FOR THE NUMBERS IS STILL `/about`. This module does not
 *  replace it — rewiring that page's JSX would risk the DESIGN-complete markup
 *  for no gain — it restates it for the two machine-readable consumers, and
 *  `tools/seo/check-llms.mjs` asserts every figure below still appears verbatim
 *  in the rendered `/en/about`. Hand-stated, but checked.
 */

/** One claim, and the shape it takes on `/about`'s trust strip. */
export type CompanyFact = {
  /** The figure exactly as `/about` renders it — the string the checker greps. */
  readonly value: string;
  readonly label: string;
};

export const COMPANY_FACTS: readonly CompanyFact[] = [
  { value: "2018", label: "founded" },
  { value: "20M+", label: "checks completed" },
  { value: "2,000+", label: "clients" },
  { value: "120+", label: "countries" },
  { value: "6", label: "offices" },
];

/** The six offices, in the order `/about` lists them. Noida is the head office
 *  and is the `addressLocality` on the `Organization` node. */
export const OFFICES: readonly string[] = [
  "Noida, India (head office)",
  "Manila, Philippines",
  "Singapore",
  "Dubai, UAE",
  "Cairo, Egypt",
  "New York, United States",
];

/** Public contact details, ported from the old site's contact-page CMS
 *  (`public/cms/en/contactUs.base.json`) and its `StructuredData.tsx`.
 *
 *  These are the fields §11a.3 calls the entity-disambiguation lever, and they
 *  were the item-6 blocker: nothing in THIS repo carried a phone number, a
 *  public email or a real social URL, so the `Organization` node shipped
 *  without them rather than with guesses. The old repo carries all three.
 */
export const CONTACT = {
  /** The general enquiry address, on the old `Organization` node and in the old
   *  `llms.txt`. `privacy@helloverify.com` is the data-protection contact and
   *  stays on the pages that use it; `support@` is below. */
  salesEmail: "hello@helloverify.com",
  supportEmail: "support@helloverify.com",
  /** E.164, because schema.org asks for it and no crawler will reformat
   *  "+91 9289 6276 22" for you. Same digits, from the old contact page. */
  indiaPhone: "+919289627622",
  uaePhone: "+97145741066",
} as const;

/** External profiles, for `Organization.sameAs` — §11a.3's entity
 *  disambiguation, and the single highest-value field on that node. Every URL
 *  here is one the old site already publishes, so none of them is a guess. */
export const PROFILES: readonly { label: string; url: string }[] = [
  { label: "LinkedIn", url: "https://www.linkedin.com/company/helloverify" },
  { label: "Facebook", url: "https://www.facebook.com/HelloVerify/" },
  { label: "Instagram", url: "https://www.instagram.com/helloverify" },
];

/** Just the URLs, for `Organization.sameAs`, which takes bare strings. */
export const SAME_AS: readonly string[] = PROFILES.map((p) => p.url);

/** Credentials, merged from `/about` and the old `llms.txt`'s "Trust &
 *  compliance" block. `Organization` emits the three ISO standards as
 *  `Certification` nodes and PBSA as `memberOf`; the distinction matters and is
 *  argued there. NSR is a registry HelloVerify participates in and the Ministry
 *  of Manpower is a customer, so neither is claimed as an accreditation.
 *
 *  THIS IS THE REVIEWED LIST, and it is now load-bearing in two directions
 *  (BUILD-SPEC §11a.3, §11a.4). `lib/seo/llms.ts` emits it verbatim into
 *  `llms.txt`, and `tools/seo/check-llms.mjs` derives its allowed-certification
 *  set FROM this array — so a certification named anywhere in `llms.txt` and
 *  absent here fails the build. Adding a line here is therefore how a claim
 *  gets published, and the only way; the gate is not a list of two forbidden
 *  names that can be edited around.
 *
 *  ISO/IEC 27701, SOC 2 AND ISO 9001 REST ON WEAKER EVIDENCE THAN THE REST OF
 *  THIS LIST, and that is recorded rather than smoothed over. ISO 27001, PBSA,
 *  NSR and the MOM programme each trace to an artefact this business can produce
 *  on request (`platform/security-compliance`'s artefact table names them).
 *  These three trace to "the previous site published them and the owner
 *  confirmed on 22 Sep 2026" — published on the existing site at
 *  `public/llms.txt:67` (27701), `src/config/seo.ts:50` (SOC 2) and
 *  `public/cms/en/educationAuthorities.base.json:126` (ISO 9001, as "ISO 9001
 *  and 27701 certified") in `D:\Projects\Application Frontend HV`. That is a
 *  real source and it is why they are here, but it is testimony, not a
 *  certificate on file, and neither the old repo nor this one holds a
 *  certificate, an audit report or an auditor name for any of the three. **If a
 *  certificate or SOC 2 report is ever produced, replace this paragraph with a
 *  citation of it** — the issuing body, the scope statement and the date — and
 *  add the artefacts to that table. Until then the wording is deliberately the
 *  old site's own: "certified" for 27701 and for ISO 9001 because that is the
 *  word it publishes, and "compliant" for SOC 2 for the same reason, since a
 *  SOC 2 engagement produces an attestation report rather than a certificate
 *  and upgrading it to "certified" here would be this file inventing a claim.
 *
 *  ISO 9001 CAME LAST AND FOR A REASON WORTH KEEPING. It was not on the 22 Sep
 *  shortlist at all; the `check:llms` rewrite in that same change used it as its
 *  worked example of a claim the old denylist would have let through, which is
 *  how `educationAuthorities.base.json:126` was read closely enough to notice
 *  the old site publishes it. So the gate found the claim and the owner then
 *  confirmed it — the order matters, because it means the gate is doing the job
 *  it was written for rather than only the one it was tested on.
 *
 *  AND THERE IS STILL NO ISO 9001 BADGE, despite appearances. The old repo
 *  references `/assets/aboutus/ISO_9001_1.png` from
 *  `public/cms/{en,hi,ar}/globals.base.json:51,55`, and the file exists — but it
 *  depicts a generic blue ISO roundel captioned **27001**, not 9001. The
 *  filename is simply wrong, and the same file is used for BOTH badge slots in
 *  that logo strip while `public/assets/aboutus/ISO_27001_1.png` beside it — a
 *  real TÜV SÜD mark reading "ISO 27001" — is referenced nowhere. So
 *  `/img/iso-9001.jpg` here is a typographic plate like 27701's and SOC 2's,
 *  not ported artwork: publishing a 27001 roundel captioned as ISO 9001 would
 *  be a picture of a different standard. Worth knowing separately: that TÜV SÜD
 *  mark names an actual certification body for 27001, which is the first
 *  evidence in either repo of WHO issued anything — see the `issuedBy` note in
 *  `lib/seo/schema/organization.ts`.
 */
export const CREDENTIALS: readonly string[] = [
  "ISO 27001 certified — information security management, independently audited",
  "ISO/IEC 27701 certified — privacy information management, extending ISO 27001 to personal data",
  "SOC 2 compliant — service-organisation controls for security, availability and confidentiality",
  "ISO 9001 certified — quality management systems, covering how service delivery is documented, measured and improved",
  "GDPR-aligned data protection practices",
  "PBSA member — the global standards body for the screening industry",
  "National Skills Registry — India's registry of verified IT and ITeS professionals",
  "Primary source verification with auditable, forgery-protected reports",
  "In production with Singapore's Ministry of Manpower for work-pass credential verification",
  "Backed by Y Combinator",
];

/** The four status words, and there are exactly four on purpose.
 *
 *  `/platform/security-compliance`'s section standfirst reads "Certified,
 *  compliant, aligned and member are four different claims. We don't blur
 *  them — a reviewer who catches a vendor overstating one stops trusting the
 *  rest." That sentence is a COUNT of the rows below it, so this union is the
 *  type that makes the count true: a fifth word cannot reach a card without
 *  editing this line, and whoever edits it has to go and read that standfirst.
 *
 *  It is not hypothetical. `/platform/security-compliance` shipped a fifth —
 *  "NSR — empanelled" — which contradicted its own standfirst and claimed a
 *  standing `CREDENTIALS` deliberately does not claim (see the note above: NSR
 *  is a registry HelloVerify participates in, not an accreditation). Measured
 *  22 Sep 2026, fixed in the same change as this type.
 */
export type CredentialStatus = "certified" | "compliant" | "aligned" | "member";

/** One `.cert` card: the logo, the heading and the one line under it. */
export type CredentialMark = {
  /** The logo, from `/public/img`. */
  readonly img: string;
  /** The credential, spelled as `CREDENTIALS` above spells it. */
  readonly name: string;
  /** The reviewed status word, or absent where the reviewed list claims none —
   *  NSR and the Ministry of Manpower reference. Absent is a claim too: it is
   *  the claim that this is participation rather than accreditation. */
  readonly status?: CredentialStatus;
  /** `alt` where it should not be the name: NSR's logo is the three letters,
   *  and the MOM card's heading names no ministry. Defaults to `name`. */
  readonly alt?: string;
  /** Joiner between name and status on the plain heading. Only GDPR needs it:
   *  "GDPR-aligned" is a compound adjective, and `CREDENTIALS` writes it that
   *  way too ("GDPR-aligned data protection practices"). Defaults to a space. */
  readonly sep?: string;
  /** Scope words after the status on the plain heading, again GDPR only:
   *  "GDPR-aligned" alone reads as a fragment where "ISO 27001 certified"
   *  does not. Never rendered in the `dash` form, which sets the status word
   *  off by itself on purpose. */
  readonly scope?: string;
  /** The default one-liner. Taken from this credential's own tail in
   *  `CREDENTIALS` above wherever it has one, so the card and the crawler say
   *  the same words rather than two paraphrases of them. Overridable per
   *  surface — see `components/chrome/CertCard.tsx` for why. */
  readonly gloss: string;
};

/** THE SAME CREDENTIALS, IN THE SHAPE THE PAGES RENDER THEM (BUILD-SPEC
 *  §11a.3, §4 rule 2). `CREDENTIALS` above is prose for a crawler reading a
 *  bullet list; this is the `.cert` card. The two are renderings of one list,
 *  not two lists.
 *
 *  WHY THIS EXISTS: the cards were hand-written **29 times across 9 files** and
 *  they had drifted. Measured 22 Sep 2026, before this table:
 *
 *  - The homepage (`components/sections/Compliance.tsx`) showed **four**
 *    credentials where `/about` and `/platform/security-compliance` showed
 *    **seven**. The three lines added on 22 Sep (TASKS 2b) reached the two
 *    pages that rule names and stopped there.
 *  - The homepage said **"GDPR compliant"**, and so did `/business/enterprise`
 *    — on the card AND in its answer block — against "GDPR — aligned" on
 *    `/platform/security-compliance`, whose standfirst says in so many words
 *    that it does not blur those two. Two surfaces blurred them.
 *  - PBSA had two headings: "PBSA member" on five surfaces and "Professional
 *    Background Screening Association" on two. The homepage **disagreed with
 *    itself** — `.dsk` and `.mob` are separate markup (§17 condition 22, and
 *    the Part 6 finding that only the homepage is a two-tree port), and each
 *    block had its own answer.
 *  - NSR carried a fifth status word on one surface: see `CredentialStatus`.
 *  - The two seven-card pages were not the same seven: `/about` has no GDPR
 *    card and `/platform/security-compliance` has no Ministry of Manpower
 *    card. Both gaps are recorded in TASKS and deliberately NOT closed here —
 *    which cards a page shows is an editorial choice about that page, and this
 *    task was scoped to make the surfaces agree on what each card SAYS.
 *
 *  SO NAME AND STATUS COME FROM HERE, AND THE GLOSS COMES FROM HERE BY
 *  DEFAULT. Nine files cannot disagree about a string none of them holds.
 *
 *  THE INVARIANT AGAINST `CREDENTIALS`, measured rather than asserted: the
 *  CLAIM a mark makes — `name` + `sep` + `status`, or just `name` where there
 *  is no status — is a substring of exactly one `CREDENTIALS` entry. Checked
 *  22 Sep 2026 by importing both and matching: **7 of 8, one match each**, with
 *  `mom` the one miss and expected (its heading "In production with a ministry"
 *  paraphrases a line that names the ministry in full, and carries no status
 *  word either way).
 *
 *  It is the claim and not the whole heading, because measuring the heading is
 *  what the first attempt did and GDPR failed it: the plain heading is
 *  "GDPR-aligned data handling" and the reviewed line is "GDPR-aligned data
 *  protection practices". Both are the same claim with different scope words
 *  after it, which is exactly why `scope` is a separate field from `status` —
 *  the status word is the reviewed part and has to match; the words that follow
 *  it are copy for the medium.
 *
 *  **NOTHING GATES THAT INVARIANT**, and that is worth saying plainly rather
 *  than leaving as a comfortable assumption. `tools/seo/check-llms.mjs` checks
 *  `llms.txt` against `CREDENTIALS`; no check reads this table. The reason the
 *  drift above took months to notice is that it was spread over nine files, and
 *  that failure mode is now gone — a wrong status word here is wrong on one
 *  screen, in one record, in the file a reviewer reads for credentials. That is
 *  a much smaller hazard, not a closed one.
 *
 *  DERIVING `CREDENTIALS` FROM THESE RECORDS WAS TRIED AND REJECTED. Five of
 *  its ten lines are not `name status — gloss` shaped ("GDPR-aligned data
 *  protection practices", "Primary source verification with auditable,
 *  forgery-protected reports", "Backed by Y Combinator"), and the mechanical
 *  transform that fits the other five — lowercase the gloss's first letter —
 *  breaks on "India's" and on PBSA's "Member of…". `lib/seo/llms.ts` emits that
 *  array verbatim and `check-llms.mjs` derives its allowlist from it, so its
 *  bytes are reviewed copy for a crawler, not a rendering of a card.
 */
export const CREDENTIAL_MARKS = {
  iso27001: {
    img: "/img/iso.jpg",
    name: "ISO 27001",
    status: "certified",
    gloss: "Information security management, independently audited.",
  },
  iso27701: {
    img: "/img/iso-27701.jpg",
    name: "ISO/IEC 27701",
    status: "certified",
    gloss: "Privacy information management, extending ISO 27001 to personal data.",
  },
  soc2: {
    img: "/img/soc2.jpg",
    name: "SOC 2",
    status: "compliant",
    gloss: "Service-organisation controls for security, availability and confidentiality.",
  },
  iso9001: {
    img: "/img/iso-9001.jpg",
    name: "ISO 9001",
    status: "certified",
    gloss:
      "Quality management systems, covering how service delivery is documented, measured and improved.",
  },
  gdpr: {
    img: "/img/gdpr.jpg",
    name: "GDPR",
    status: "aligned",
    sep: "-",
    scope: " data handling",
    gloss: "Consent, retention limits and the right to be forgotten, in every workflow.",
  },
  pbsa: {
    img: "/img/pbsa.jpg",
    name: "PBSA",
    status: "member",
    gloss: "The global standards body for the screening industry.",
  },
  nsr: {
    img: "/img/nsr.jpg",
    name: "National Skills Registry",
    alt: "NSR",
    gloss: "India's registry of verified IT and ITeS professionals.",
  },
  mom: {
    img: "/img/mom.jpg",
    name: "In production with a ministry",
    alt: "Ministry of Manpower, Singapore",
    gloss: "Work-pass credential verification with Singapore's Ministry of Manpower.",
  },
} as const satisfies Record<string, CredentialMark>;

/** Which card, named at the call site. Every surface lists the ids it shows,
 *  the way `components/sections/Checks.tsx` names the check ids it shows rather
 *  than deriving one view's order from the other's (Part 5). A subset is a
 *  legitimate editorial choice — `/governments` leads with the artefacts a
 *  ministry asks for and does not show India's NSR — and naming the ids makes
 *  each page's choice explicit instead of implicit in 29 copies of markup. */
export type CredentialId = keyof typeof CREDENTIAL_MARKS;

/** The card heading, in the two forms the site uses, both built from `name` and
 *  `status` so no surface can pair a credential with a status the reviewed list
 *  does not give it.
 *
 *  `plain` is what eight surfaces render. `dash` is
 *  `/platform/security-compliance`'s, and it is a real difference rather than a
 *  formatting whim: that page exists to be read by a procurement reviewer, its
 *  heading is "What we hold, stated precisely", and setting the status word off
 *  with an em dash is what "precisely" means there. It drops `scope` for the
 *  same reason — "GDPR — aligned" is the claim; "data handling" is scope the
 *  gloss beside it already states.
 */
export function certHeading(m: CredentialMark, form: "plain" | "dash" = "plain"): string {
  if (!m.status) return m.name;
  if (form === "dash") return `${m.name} — ${m.status}`;
  return `${m.name}${m.sep ?? " "}${m.status}${m.scope ?? ""}`;
}

/** What HelloVerify sells, ported verbatim from the old `llms.txt`'s "Core
 *  services" block.
 *
 *  Kept as prose rather than derived from the route list because it is a
 *  different cut of the same business: this answers "what do they do", and the
 *  generated page index below answers "where do I read about it". §11a.2 rates
 *  both formats highly for extraction.
 */
export const CORE_SERVICES: readonly string[] = [
  "Employment verification and criminal background checks",
  "Education and qualification verification (primary source)",
  "Healthcare professional credential verification (PSV)",
  "Immigration and visa pre-screening",
  "International background checks (120+ countries)",
  "Vendor and third-party due diligence (Certifier)",
  "Customer KYC with identity and liveness checks",
  "Instant verification via HelloV (WhatsApp and messaging)",
];

/** The quotable definition §11a.4 asks to lead with.
 *
 *  PORTED VERBATIM from the old site's `public/llms.txt`. §11a.4 says that file
 *  "is genuinely ahead of the market and must be ported", and this paragraph is
 *  the part that matters most: it is the single string a retrieval engine is
 *  most likely to quote word for word.
 *
 *  Item 7 first shipped a paragraph assembled from `/about`'s standfirst and
 *  `SITE_DESCRIPTION`, because the old repo was not available at the time. That
 *  is REPLACED rather than merged — the reviewed original beats a
 *  reconstruction, and two near-identical definitions in circulation is exactly
 *  the entity inconsistency §11a.3 warns about.
 */
export const COMPANY_DEFINITION =
  "HelloVerify is a global AI-powered background verification (BGV) company, providing fast, " +
  "accurate, and compliant screening for employment, healthcare, immigration, and enterprise " +
  "workforce programs. 20M+ verifications completed for 2000+ organizations across 120+ countries.";

/** The supporting paragraph, also ported.
 *
 *  One sentence of the original is dropped: "Public site locales: English
 *  (`/en`), Hindi (`/hi`), Arabic (`/ar`)." This site serves `en` only
 *  (`lib/i18n/routing.ts`) and the 56 `/hi` and `/ar` URLs currently 308 onto
 *  English (`lib/seo/legacy-urls.ts`). Advertising them to a crawler that
 *  handles redirects badly (§11a.1) would be AUDIT A2 in a new file. It goes
 *  back the moment those locales ship.
 */
export const COMPANY_INTRO =
  "HelloVerify delivers AI-powered background checks, primary source verification (PSV), and " +
  "authority-specific screening programs for regulators, enterprises, SMBs, and applicants " +
  "worldwide.";
