/**
 * HelloVerify AI demo — approved redesign of the canvas DEMO section
 * (design review, Sep 2026): three evidence panels and a verdict strip,
 * one-shot reveals instead of the blanking loop. Styles in pages.css.
 * Hand-authored; NOT regenerated by tools/port/build-sections.py.
 */
import { Tick } from "@/components/brand/Tick";
import { copy } from "@/lib/copy/request";
import { SECTIONS } from "@/lib/copy/sections";

/** ASYNC even though this fragment ends in a text node, which is the shape
 *  the fourth corollary in `lib/copy/index.ts` warns about - and it is
 *  allowlisted in `tools/test/copy.test.ts` §12 because five real builds
 *  measured THIS one as byte-neutral, unlike `blocks/LeadMock.tsx`'s. The
 *  junction below this band did lose a separator, and reverting this file
 *  to HEAD does not restore it; see the dated deviation in that header. */
export async function Demo2() {
  const t = (await copy(SECTIONS)).demo2;

  return (
    <>
        <div className="wrap" style={{ paddingTop: '120px' }}>
          {' '}
          <div className="sec-head">
            {' '}
            <div>
              <div className="k">
                {t.kicker}
              </div>
              <h2 className="h2" style={{ marginTop: '14px' }}>
                {t.headingA}
                <br />
                {t.headingB}
              </h2>
            </div>
            {' '}
            <p className="lede" style={{ marginBottom: '8px' }}>
              {t.lede}
            </p>
            {' '}
          </div>
          {' '}
          <div className="demo2">
            {' '}
            <div className="dring">
            </div>
            {' '}
            <div className="dcard2">
              {' '}
              <div className="dtabs">
                <span className="on">
                  {t.tabs.licence}
                </span>
                <span>
                  {t.tabs.degree}
                </span>
                <span>
                  {t.tabs.pan}
                </span>
                <span>
                  {t.tabs.passport}
                </span>
                <span className="more">
                  {t.tabs.more}
                </span>
              </div>
              {' '}
              <div className="d2grid">
                {' '}
                <div className="d2col d2scan">
                  {' '}
                  <div className="d2stage">
                    {' '}
                    <div className="lic d2">
                      <span className="lt">
                        {t.licence.title}
                      </span>
                      <span className="lr">
                        {t.licence.region}
                      </span>
                      <div className="face">
                      </div>
                      <div className="ln1">
                      </div>
                      <div className="ln2">
                      </div>
                      <div className="ln3">
                      </div>
                      <div className="ln4">
                      </div>
                      <div className="holo">
                      </div>
                    </div>
                    {' '}
                    <div className="beam d2beam">
                    </div>
                    {' '}
                  </div>
                  {' '}
                  <div className="d2cap">
                    {' '}
                    <span className="chip2">
                      <span className="dot live">
                      </span>
                      {t.scan.reading}
                    </span>
                    {' '}
                    <span>
                      {t.scan.sample}
                    </span>
                    {' '}
                  </div>
                  {' '}
                </div>
                {' '}
                <div className="d2col">
                  {' '}
                  <div className="d2h">
                    <span>
                      {t.extracted.heading}
                    </span>
                    <b>
                      {t.extracted.time}
                    </b>
                  </div>
                  {' '}
                  <div className="d2f" style={{ animationDelay: '0.15s' }}>
                    <span className="d2fl">
                      {t.fields.name.l}
                    </span>
                    <span className="d2fv">
                      {t.fields.name.v}
                    </span>
                    <Tick />
                  </div>
                  {' '}
                  <div className="d2f" style={{ animationDelay: '0.3s' }}>
                    <span className="d2fl">
                      {t.fields.dob.l}
                    </span>
                    <span className="d2fv">
                      {t.fields.dob.v}
                    </span>
                    <Tick />
                  </div>
                  {' '}
                  <div className="d2f" style={{ animationDelay: '0.45s' }}>
                    <span className="d2fl">
                      {t.fields.licence.l}
                    </span>
                    <span className="d2fv">
                      {t.fields.licence.v}
                    </span>
                    <Tick />
                  </div>
                  {' '}
                  <div className="d2f" style={{ animationDelay: '0.6s' }}>
                    <span className="d2fl">
                      {t.fields.vehicleClass.l}
                    </span>
                    <span className="d2fv">
                      {t.fields.vehicleClass.v}
                    </span>
                    <Tick />
                  </div>
                  {' '}
                  <div className="d2f" style={{ animationDelay: '0.75s' }}>
                    <span className="d2fl">
                      {t.fields.valid.l}
                    </span>
                    <span className="d2fv">
                      {t.fields.valid.v}
                    </span>
                    <Tick />
                  </div>
                  {' '}
                </div>
                {' '}
                <div className="d2col">
                  {' '}
                  <div className="d2h">
                    <span>
                      {t.checksHeading}
                    </span>
                    <b>
                      {t.checksVerdict}
                    </b>
                  </div>
                  {' '}
                  <div className="d2c" style={{ animationDelay: '0.9s' }}>
                    <Tick />
                    <span>
                      <span className="cl">
                        {t.checks.template.l}
                      </span>
                      <span className="cs">
                        {t.checks.template.s}
                      </span>
                    </span>
                    <span className="cv">
                      {t.checks.template.v}
                    </span>
                  </div>
                  {' '}
                  <div className="d2c" style={{ animationDelay: '1.05s' }}>
                    <Tick />
                    <span>
                      <span className="cl">
                        {t.checks.hologram.l}
                      </span>
                      <span className="cs">
                        {t.checks.hologram.s}
                      </span>
                    </span>
                    <span className="cv">
                      {t.checks.hologram.v}
                    </span>
                  </div>
                  {' '}
                  <div className="d2c" style={{ animationDelay: '1.2s' }}>
                    <Tick />
                    <span>
                      <span className="cl">
                        {t.checks.face.l}
                      </span>
                      <span className="cs">
                        {t.checks.face.s}
                      </span>
                    </span>
                    <span className="cv">
                      <span className="d2meter">
                        <i>
                        </i>
                      </span>
                      {t.checks.face.v}
                    </span>
                  </div>
                  {' '}
                  <div className="d2c" style={{ animationDelay: '1.35s' }}>
                    <Tick />
                    <span>
                      <span className="cl">
                        {t.checks.issuer.l}
                      </span>
                      <span className="cs">
                        {t.checks.issuer.s}
                      </span>
                    </span>
                    <span className="cv">
                      {t.checks.issuer.v}
                    </span>
                  </div>
                  {' '}
                </div>
                {' '}
              </div>
              {' '}
              <div className="d2foot">
                {' '}
                <span className="dot live">
                </span>
                {' '}
                <span>
                  <span className="fmsg">
                    {t.foot.msg}
                  </span>
                  <br />
                  <span className="fsub">
                    {t.foot.sub}
                  </span>
                </span>
                {' '}
                <span className="fright">
                  <span className="d2prog">
                    <span>
                    </span>
                  </span>
                  <span className="ftime">
                    <small>
                      {t.foot.readyIn}
                    </small>
                    {t.foot.time}
                  </span>
                </span>
                {' '}
              </div>
              {' '}
            </div>
            {' '}
          </div>
          {' '}
        </div>
        {' '}
    </>
  );
}
