/**
 * HelloVerify AI demo — approved redesign of the canvas DEMO section
 * (design review, Sep 2026): three evidence panels and a verdict strip,
 * one-shot reveals instead of the blanking loop. Styles in pages.css.
 * Hand-authored; NOT regenerated by tools/port/build-sections.py.
 */
import { Tick } from "@/components/brand/Tick";

export function Demo2() {
  return (
    <>
        <div className="wrap" style={{ paddingTop: '120px' }}>
          {' '}
          <div className="sec-head">
            {' '}
            <div>
              <div className="k">
                HelloVerify AI
              </div>
              <h2 className="h2" style={{ marginTop: '14px' }}>
                Watch it read
                <br />
                a licence.
              </h2>
            </div>
            {' '}
            <p className="lede" style={{ marginBottom: '8px' }}>
              Every document starts here. Fields, forgery checks and the issuing office — in about a second, before a person touches it.
            </p>
            {' '}
          </div>
          {' '}
          <div className="demo2">
            {' '}
            <div className="dring">
            </div>
            {' '}
            <div className="dcard2">
              {' '}
              <div className="dtabs">
                <span className="on">
                  Driving licence
                </span>
                <span>
                  Degree certificate
                </span>
                <span>
                  PAN card
                </span>
                <span>
                  Passport
                </span>
                <span className="more">
                  +29
                </span>
              </div>
              {' '}
              <div className="d2grid">
                {' '}
                <div className="d2col d2scan">
                  {' '}
                  <div className="d2stage">
                    {' '}
                    <div className="lic d2">
                      <span className="lt">
                        Driving licence
                      </span>
                      <span className="lr">
                        IND
                      </span>
                      <div className="face">
                      </div>
                      <div className="ln1">
                      </div>
                      <div className="ln2">
                      </div>
                      <div className="ln3">
                      </div>
                      <div className="ln4">
                      </div>
                      <div className="holo">
                      </div>
                    </div>
                    {' '}
                    <div className="beam d2beam">
                    </div>
                    {' '}
                  </div>
                  {' '}
                  <div className="d2cap">
                    {' '}
                    <span className="chip2">
                      <span className="dot live">
                      </span>
                      Reading · 0.9 s
                    </span>
                    {' '}
                    <span>
                      sample document
                    </span>
                    {' '}
                  </div>
                  {' '}
                </div>
                {' '}
                <div className="d2col">
                  {' '}
                  <div className="d2h">
                    <span>
                      Extracted · 14 fields
                    </span>
                    <b>
                      0.9 s
                    </b>
                  </div>
                  {' '}
                  <div className="d2f" style={{ animationDelay: '0.15s' }}>
                    <span className="d2fl">
                      Name
                    </span>
                    <span className="d2fv">
                      A. Ramesh
                    </span>
                    <Tick />
                  </div>
                  {' '}
                  <div className="d2f" style={{ animationDelay: '0.3s' }}>
                    <span className="d2fl">
                      Date of birth
                    </span>
                    <span className="d2fv">
                      14 Mar 1994
                    </span>
                    <Tick />
                  </div>
                  {' '}
                  <div className="d2f" style={{ animationDelay: '0.45s' }}>
                    <span className="d2fl">
                      Licence no.
                    </span>
                    <span className="d2fv">
                      KA03 2019 0041782
                    </span>
                    <Tick />
                  </div>
                  {' '}
                  <div className="d2f" style={{ animationDelay: '0.6s' }}>
                    <span className="d2fl">
                      Class
                    </span>
                    <span className="d2fv">
                      LMV · MCWG
                    </span>
                    <Tick />
                  </div>
                  {' '}
                  <div className="d2f" style={{ animationDelay: '0.75s' }}>
                    <span className="d2fl">
                      Valid till
                    </span>
                    <span className="d2fv">
                      13 Mar 2039
                    </span>
                    <Tick />
                  </div>
                  {' '}
                </div>
                {' '}
                <div className="d2col">
                  {' '}
                  <div className="d2h">
                    <span>
                      Checks
                    </span>
                    <b>
                      All clear
                    </b>
                  </div>
                  {' '}
                  <div className="d2c" style={{ animationDelay: '0.9s' }}>
                    <Tick />
                    <span>
                      <span className="cl">
                        Template{' '}
                        &amp;
                        {' '}fonts
                      </span>
                      <span className="cs">
                        against Karnataka 2019 series
                      </span>
                    </span>
                    <span className="cv">
                      match
                    </span>
                  </div>
                  {' '}
                  <div className="d2c" style={{ animationDelay: '1.05s' }}>
                    <Tick />
                    <span>
                      <span className="cl">
                        Hologram{' '}
                        &amp;
                        {' '}microtext
                      </span>
                      <span className="cs">
                        tamper scan
                      </span>
                    </span>
                    <span className="cv">
                      clear
                    </span>
                  </div>
                  {' '}
                  <div className="d2c" style={{ animationDelay: '1.2s' }}>
                    <Tick />
                    <span>
                      <span className="cl">
                        Face vs. selfie
                      </span>
                      <span className="cs">
                        liveness passed
                      </span>
                    </span>
                    <span className="cv">
                      <span className="d2meter">
                        <i>
                        </i>
                      </span>
                      98%
                    </span>
                  </div>
                  {' '}
                  <div className="d2c" style={{ animationDelay: '1.35s' }}>
                    <Tick />
                    <span>
                      <span className="cl">
                        Issuer located
                      </span>
                      <span className="cs">
                        registry reachable
                      </span>
                    </span>
                    <span className="cv">
                      RTO Karnataka
                    </span>
                  </div>
                  {' '}
                </div>
                {' '}
              </div>
              {' '}
              <div className="d2foot">
                {' '}
                <span className="dot live">
                </span>
                {' '}
                <span>
                  <span className="fmsg">
                    Route: confirm at the source
                  </span>
                  <br />
                  <span className="fsub">
                    a person takes it from here — RTO Karnataka
                  </span>
                </span>
                {' '}
                <span className="fright">
                  <span className="d2prog">
                    <span>
                    </span>
                  </span>
                  <span className="ftime">
                    <small>
                      Ready in
                    </small>
                    30 min
                  </span>
                </span>
                {' '}
              </div>
              {' '}
            </div>
            {' '}
          </div>
          {' '}
        </div>
        {' '}
    </>
  );
}
