"use client";

/** The live network in the Trust Platform section (`./TrustPlatform`): an
    Obsidian-style force graph on a 2D canvas, with the HelloVerify medallion
    at its hub and a slider that rewinds it from 2018 to today.

    Ported from the canvas board's `nwInit`/`nwFrame` (Desktop4, generated by
    `assemble_graph.py`); the physics constants, timings and drawing order are
    the board's, unchanged, and live in `lib/trustNetworkSim.ts`. This file
    owns the DOM, the slider and the pause context. What changed for
    production:

    1. **Colours come from CSS custom properties**, read once when the loop
       starts (`--green`, `--green-light`, `--ink`, `--white`, and the two
       `--v2-tq-*` hover tints declared in `app/v2/platform.css`). The board
       typed hex into the drawing code; `hv/no-color-literal` forbids that,
       and a re-theme should not need a JS edit.
    2. **The loop stops, rather than idles.** The board kept requesting frames
       offscreen and skipped the work; here an IntersectionObserver cancels the
       frame loop when the stage leaves the viewport. With motion paused (the
       section's control, via `MotionPaused`) or `prefers-reduced-motion`, the
       graph is drawn calm — no drift, no signals, no staggered growth — and
       the loop runs only while something is actually moving (a drag, a hover,
       nodes settling after a rewind), then stops.
    3. **Hydration-safe.** The server renders an empty canvas and the slider
       at "Today"; everything random (signal timing, growth jitter) happens in
       effects and event handlers, never in render output.

    The canvas is `role="img"` with a name; the interaction (hover, drag) is
    an enhancement for pointers. The slider is the one control and is a native
    range input with a label and an `aria-valuetext` of the year. */

import { useContext, useEffect, useRef, useState, type PointerEvent, type ReactNode } from "react";
import type { TrustNetworkSim } from "@/lib/trustNetworkSim";
import { LAST } from "@/lib/trustNetworkSteps";
import { whenNear } from "@/lib/whenNear";
import { MotionPaused } from "./TrustPlatformStage";

/** The drawing box, in canvas units; CSS scales it to the 700×500 stage. */
const W = 700;
const H = 500;

export type NetworkCopy = {
  canvas: string;
  hint: string;
  rewind: string;
  today: string;
  node: { institution: string; customer: string; one: string; many: string };
};

const yearOf = (step: number, today: string) => (step >= LAST ? today : String(2018 + step));

export function TrustNetwork({ t, children }: { t: NetworkCopy; children: ReactNode }) {
  const paused = useContext(MotionPaused);
  const [net, setNet] = useState(LAST);
  const stageRef = useRef<HTMLDivElement>(null);
  const cvRef = useRef<HTMLCanvasElement>(null);
  /** The simulation (`lib/trustNetworkSim`) is built once, after mount, and
   *  reads the slider and the pause state through these refs, so a pointer
   *  move or a frame costs no React render. */
  const sim = useRef<TrustNetworkSim | null>(null);
  const tRef = useRef(t);
  const netRef = useRef(net);
  const pausedRef = useRef(paused);
  useEffect(() => {
    netRef.current = net;
    pausedRef.current = paused;
    sim.current?.refresh();
  }, [net, paused]);

  useEffect(() => {
    const cv = cvRef.current;
    const stage = stageRef.current;
    if (!cv || !stage) return;
    // The simulation and its graph table load as the stage approaches, not
    // with the page (`lib/whenNear`).
    return whenNear(stage, () => import("@/lib/trustNetworkSim"), ({ createTrustNetwork }) => {
      const s = createTrustNetwork(cv, stage, {
        net: () => netRef.current,
        paused: () => pausedRef.current,
        copy: tRef.current.node,
      });
      sim.current = s;
      return () => {
        s?.destroy();
        sim.current = null;
      };
    });
  }, []);

  const call = (k: "down" | "move" | "up" | "leave", e: PointerEvent<HTMLDivElement>) => sim.current?.[k](e);

  const year = yearOf(net, t.today);

  return (
    <>
      <div
        ref={stageRef}
        className="tq-stage"
        onPointerDown={(e) => call("down", e)}
        onPointerMove={(e) => call("move", e)}
        onPointerUp={(e) => call("up", e)}
        onPointerCancel={(e) => call("up", e)}
        onPointerLeave={(e) => call("leave", e)}
      >
        <canvas ref={cvRef} className="tq-cv" width={W} height={H} role="img" aria-label={t.canvas} />
        {children}
        <span className="tq-hint" aria-hidden="true">{t.hint}</span>
        {/* The slider's `aria-valuetext` already announces the year, so the
            big numeral is not a second live region saying it again. */}
        <div className="tq-year" aria-hidden="true">{year}</div>
      </div>
      <div className="tq-scrub">
        <label className="tq-scrub-l" htmlFor="tq-range">{t.rewind}</label>
        <input
          id="tq-range"
          className="tq-range"
          type="range"
          min={0}
          max={LAST}
          step={1}
          value={net}
          onChange={(e) => setNet(parseInt(e.target.value, 10) || 0)}
          aria-valuetext={year}
        />
        <div className="tq-ticks" aria-hidden="true">
          {[0, 2, 4, 6, 8].map((s) => <span key={s}>{yearOf(s, t.today)}</span>)}
        </div>
      </div>
    </>
  );
}
